=== atuowgo/ParallelPreTreatment/src/main/framework/JobRepo/jobConf.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.w3school.com.cn"
        xmlns="http://www.w3school.com.cn"
        elementFormDefault="qualified">

    <xs:simpleType name="pathType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="continueToType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="featureNumType">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>
    <xs:simpleType name="fetureNumType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="markType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="trainPercentageType">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="100"/>
            <xs:minInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="jobNameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:attributeGroup name="mainAttr">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="continueto" type="continueToType"/>
    </xs:attributeGroup>


    <xs:complexType name="startElementType">
        <xs:complexContent>
            <xs:restriction base="xs:string">
                <xs:attribute name="continueto" type="continueToType"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="taskElementType">
        <xs:complexContent>
            <xs:restriction base="xs:string">
                <xs:attributeGroup ref="mainAttr"/>
                <xs:attribute name="trainPecentage" type="trainPercentageType"/>
                <xs:attribute name="fetureNum" type="fetureNumType"/>
                <xs:attribute name="featureNum" type="featureNumType"/>
                <xs:attribute name="markStr" type="markType"/>
                <xs:attribute name="localOutputPath" type="pathType"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="endElementType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="jobType">
        <xs:sequence>
            <xs:element name="start" type="startElementType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="task" type="taskElementType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="end" type="endElementType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="jobNameType"/>
    </xs:complexType>

    <xs:element name="job" type="jobType"/>

</xs:schema>

=== atuowgo/ParallelPreTreatment/out/production/ParallelPreTreatment/main/framework/JobRepo/job-conf.xml
<?xml version="1.0"?>
<!--<job name="defJob"-->
<!--xmlns="http://www.w3school.com.cn"-->
<!--xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<!--xsi:schemaLocation="http://www.w3school.com.cn jobConf.xsd">-->
<!--<start continueto="defTest"></start>-->
<!--<task name="defTest" continueto="defClean"></task>-->
<!--<task name="defClean" trainPecentage="60" continueto="defToken"></task>-->

<!--<task name="defToken" continueto="defDFFeature"></task>-->
<!--<task name="defDFFeature" fetureNum="20000" continueto="defMatrix"></task>-->

<!--<task name="defMatrix" continueto="defNB"></task>-->
<!--<task name="defNB"-->
<!--markStr="defNB_DF_20000"-->
<!--localOutputPath="/home/adam/dev/tmp/mahoutLocalOut/df"-->
<!--continueto="end"></task>-->
<!--<end></end>-->
<!--</job>-->


<job name="defJob"
xmlns="http://www.w3school.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn jobConf.xsd">
    <start continueto="defTest"></start>
    <task name="defTest" continueto="defClean"></task>
    <task name="defClean" trainPecentage="50" continueto="defToken"></task>

    <task name="defToken" continueto="defECEFeature"></task>
    <task name="defECEFeature" featureNum="100" continueto="defMatrix"></task>

    <task name="defMatrix" continueto="defNB"></task>
    <task name="defNB"
          markStr="defNB_ECE_100"
          localOutputPath="/home/adam/dev/tmp/mahoutLocalOut/ece"
          continueto="end"></task>
    <end></end>
</job>
